In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
# store the feature matrix (x) and response vector(y)
X = iris.data
y = iris.target

In [3]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
#check the shape of X and y

print (X.shape)
print (y.shape)

(150, 4)
(150,)


In [5]:
import pandas as pd
pd.DataFrame(X, columns = iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
# Print the response vector
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
#import the calssification model

from sklearn.neighbors import KNeighborsClassifier

#instantiate the model
knn = KNeighborsClassifier()

#fit the data
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [8]:
#predict the response for a new observation

knn.predict([[3, 5, 4, 2]])

array([1])

In [9]:
# example text for model training (SMS messages)

simple_train = ['call you tonight','Call me a cab','please call me... PLEASE!']

In [10]:
#import and initiate CounteVectorizer 
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [11]:
#learn the vocablury of the training data
vect.fit(simple_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [12]:
# examine the fitted vocublary
vect.get_feature_names()

['cab', 'call', 'me', 'please', 'tonight', 'you']

In [13]:
# transform training data into a 'document-term-matrix
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [14]:
#convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [15]:
pd.DataFrame(simple_train_dtm.toarray(), columns = vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [16]:
print (simple_train_dtm)

#We use a sparse array because it is memory efficient. It only stores the data of non-zero values
print (type(simple_train_dtm))

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2
<class 'scipy.sparse.csr.csr_matrix'>


In [17]:
# example text for model testing
sample_text = ["please don't call me"]

In [18]:
# transform the testing data
sample_text_dtm = vect.transform(sample_text)
sample_text_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]])

In [19]:
pd.DataFrame(sample_text_dtm.toarray(), columns = vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

In [20]:
path = '../datasets/sms.tsv'
sms = pd.read_table(path, header = None, names = ['label','messages'])

In [21]:
sms.shape

(5572, 2)

In [22]:
sms.head(10)

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [23]:
# examine the class distribution
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [24]:
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [25]:
sms.head()

label                                           messages  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [26]:
X = sms.messages
y = sms.label_num
#In this case the feature matix is one dimensional because the CountVectorizer will convert the one-D array into 2-D array

print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [27]:
#split the data into training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

In [28]:
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(4179,)
(1393,)
(4179,)
(1393,)


In [29]:
vect = CountVectorizer()
vect.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [30]:
X_train_dtm = vect.transform(X_train)
X_train_dtm

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [31]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

Now we are slecting a model, which is Multinomial

In [32]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [33]:
%time nb.fit(X_train_dtm, y_train)

CPU times: user 7.18 ms, sys: 0 ns, total: 7.18 ms
Wall time: 6.48 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
# make prediction upon the tes_data

y_pred_class = nb.predict(X_test_dtm)

In [35]:
#calculate th eaccuracy

from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.9885139985642498

In [39]:
#print the confusion matrixmetrics
metrics.confusion_matrix(y_test, y_pred_class)

array([[1203,    5],
       [  11,  174]])

In [40]:
# printing false positives
X_test[(y_pred_class==1) & (y_test==0)] #X_test[y_pred_class > y_test]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: messages, dtype: object

In [41]:
# printing false negatives
X_test[(y_pred_class == 0) & (y_test==1)] #X_test[y_pred_calss < y_test]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: messages, dtype: object

In [43]:
#calculate predicted probabilities for X_test_dtm (poorly calibrated)
y_pred_prob = nb.predict_proba(X_test_dtm)[:,1]
y_pred_prob

array([2.87744864e-03, 1.83488846e-05, 2.07301295e-03, ...,
       1.09026171e-06, 1.00000000e+00, 3.98279868e-09])

In [45]:
#calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.9866431000536962

Now we will be comapring the model with LogisticRegresson model

In [49]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [52]:
# train the model
%time logreg.fit(X_train_dtm, y_train)

CPU times: user 35.1 ms, sys: 0 ns, total: 35.1 ms
Wall time: 40 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [53]:
#predict 
y_pred = logreg.predict(X_test_dtm)

In [55]:
##accuracy
metrics.accuracy_score(y_test, y_pred)

0.9877961234745154

In [56]:
# calculate predicted probabilities for X_test_dtm
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([0.01269556, 0.00347183, 0.00616517, ..., 0.03354907, 0.99725053,
       0.00157706])

In [58]:
#calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.9936817612314301

In [59]:
# store the vocablury of X_train

X_train_tokens = vect.get_feature_names()
len(X_train_tokens)

7456

In [60]:
#examine the first 50 elements
print (X_train_tokens[0:50])

['00', '000', '008704050406', '0121', '01223585236', '01223585334', '0125698789', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07090201529', '07090298926', '07123456789', '07732584351', '07734396839', '07742676969', '0776xxxxxxx', '07781482378', '07786200117', '078', '07801543489', '07808', '07808247860', '07808726822', '07815296484', '07821230901', '07880867867', '0789xxxxxxx', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705']


In [62]:
#examine the last 50 tokens
print(X_train_tokens[-50:])

['yer', 'yes', 'yest', 'yesterday', 'yet', 'yetunde', 'yijue', 'ym', 'ymca', 'yo', 'yoga', 'yogasana', 'yor', 'yorge', 'you', 'youdoing', 'youi', 'youphone', 'your', 'youre', 'yourjob', 'yours', 'yourself', 'youwanna', 'yowifes', 'yoyyooo', 'yr', 'yrs', 'ything', 'yummmm', 'yummy', 'yun', 'yunny', 'yuo', 'yuou', 'yup', 'zac', 'zaher', 'zealand', 'zebra', 'zed', 'zeros', 'zhong', 'zindgi', 'zoe', 'zoom', 'zouk', 'zyada', 'èn', '〨ud']


In [63]:
#Naive Byes counts the number of times each token appears in each class
nb.feature_count_
#Basically it tells us that how many times a token appeared in the '0'(spam class) and '1'(ham class)

array([[ 0.,  0.,  0., ...,  1.,  1.,  1.],
       [ 5., 23.,  2., ...,  0.,  0.,  0.]])

In [64]:
#no of times each token appears across all ham messages
ham_token_count = nb.feature_count_[0, :]

#no of times each token appears across all spam messages
spam_token_count = nb.feature_count_[1, :]

In [73]:
tokens = pd.DataFrame({'token': X_train_tokens, 'ham': ham_token_count, 'spam': spam_token_count})
tokens = tokens.set_index('token')
tokens.head()

ham  spam
token                  
00            0.0   5.0
000           0.0  23.0
008704050406  0.0   2.0
0121          0.0   1.0
01223585236   0.0   1.0

In [74]:
tokens.sample(5, random_state = 6)

ham  spam
token                   
very          64.0   2.0
nasty          1.0   1.0
villa          0.0   1.0
beloved        1.0   0.0
textoperator   0.0   2.0

In [75]:
#no of observations in each class
nb.class_count_

array([3617.,  562.])

In [76]:
#we are doign this avoid zero in our calc
tokens.ham += 1
tokens.spam += 1
tokens.sample(5, random_state = 6)

ham  spam
token                   
very          65.0   3.0
nasty          2.0   2.0
villa          1.0   2.0
beloved        2.0   1.0
textoperator   1.0   3.0

In [79]:
#frequency
tokens['ham_freq'] = tokens.ham / nb.class_count_[0]
tokens['spam_freq'] = tokens.spam / nb.class_count_[1]

tokens.sample(5, random_state = 6)

ham  spam  ham_freq  spam_freq
token                                        
very          65.0   3.0  0.017971   0.005338
nasty          2.0   2.0  0.000553   0.003559
villa          1.0   2.0  0.000276   0.003559
beloved        2.0   1.0  0.000553   0.001779
textoperator   1.0   3.0  0.000276   0.005338

In [81]:
tokens['spam_ratio'] = tokens.spam_freq / tokens.ham_freq 
tokens.sample(5, random_state = 6)

ham  spam  ham_freq  spam_freq  spam_ratio
token                                                    
very          65.0   3.0  0.017971   0.005338    0.297044
nasty          2.0   2.0  0.000553   0.003559    6.435943
villa          1.0   2.0  0.000276   0.003559   12.871886
beloved        2.0   1.0  0.000553   0.001779    3.217972
textoperator   1.0   3.0  0.000276   0.005338   19.307829

In [84]:
#sorting the values using sapm ratio

tokens.sort_values('spam_ratio', ascending = False)

ham  spam  ham_freq  spam_freq  spam_ratio
token                                                   
claim         1.0  89.0  0.000276   0.158363  572.798932
prize         1.0  76.0  0.000276   0.135231  489.131673
150p          1.0  49.0  0.000276   0.087189  315.361210
tone          1.0  48.0  0.000276   0.085409  308.925267
guaranteed    1.0  43.0  0.000276   0.076512  276.745552
18            1.0  39.0  0.000276   0.069395  251.001779
cs            1.0  37.0  0.000276   0.065836  238.129893
www           2.0  73.0  0.000553   0.129893  234.911922
1000          1.0  32.0  0.000276   0.056940  205.950178
awarded       1.0  30.0  0.000276   0.053381  193.078292
150ppm        1.0  29.0  0.000276   0.051601  186.642349
uk            2.0  56.0  0.000553   0.099644  180.206406
500           1.0  27.0  0.000276   0.048043  173.770463
ringtone      1.0  25.0  0.000276   0.044484  160.898577
000           1.0  24.0  0.000276   0.042705  154.462633
mob           1.0  24.0  0.000276   0.042705  154.462633
co            2.0  44.0  0.000553   0.078292  141.590747
collection    1.0  22.0  0.000276   0.039146  141.590747
valid         1.0  21.0  0.000276   0.037367  135.154804
2000          1.0  21.0  0.000276   0.037367  135.154804
800           1.0  21.0  0.000276   0.037367  135.154804
10p           1.0  21.0  0.000276   0.037367  135.154804
8007          1.0  20.0  0.000276   0.035587  128.718861
16            2.0  38.0  0.000553   0.067616  122.282918
weekly        1.0  19.0  0.000276   0.033808  122.282918
tones         1.0  18.0  0.000276   0.032028  115.846975
land          1.0  18.0  0.000276   0.032028  115.846975
http          1.0  18.0  0.000276   0.032028  115.846975
national      1.0  17.0  0.000276   0.030249  109.411032
5000          1.0  17.0  0.000276   0.030249  109.411032
...           ...   ...       ...        ...         ...
went         46.0   1.0  0.012718   0.001779    0.139912
ll          190.0   4.0  0.052530   0.007117    0.135494
told         50.0   1.0  0.013824   0.001779    0.128719
feel         50.0   1.0  0.013824   0.001779    0.128719
gud          51.0   1.0  0.014100   0.001779    0.126195
cos          54.0   1.0  0.014929   0.001779    0.119184
but         328.0   6.0  0.090683   0.010676    0.117731
amp          55.0   1.0  0.015206   0.001779    0.117017
something    55.0   1.0  0.015206   0.001779    0.117017
sure         55.0   1.0  0.015206   0.001779    0.117017
ok          221.0   4.0  0.061100   0.007117    0.116488
said         59.0   1.0  0.016312   0.001779    0.109084
morning      61.0   1.0  0.016865   0.001779    0.105507
yeah         64.0   1.0  0.017694   0.001779    0.100562
lol          64.0   1.0  0.017694   0.001779    0.100562
anything     65.0   1.0  0.017971   0.001779    0.099015
my          544.0   8.0  0.150401   0.014235    0.094646
doing        69.0   1.0  0.019077   0.001779    0.093275
way          71.0   1.0  0.019630   0.001779    0.090647
ask          71.0   1.0  0.019630   0.001779    0.090647
already      71.0   1.0  0.019630   0.001779    0.090647
too          79.0   1.0  0.021841   0.001779    0.081468
come        177.0   2.0  0.048936   0.003559    0.072723
later       111.0   1.0  0.030688   0.001779    0.057981
lor         119.0   1.0  0.032900   0.001779    0.054084
da          119.0   1.0  0.032900   0.001779    0.054084
she         129.0   1.0  0.035665   0.001779    0.049891
he          170.0   1.0  0.047000   0.001779    0.037858
lt          232.0   1.0  0.064142   0.001779    0.027741
gt          235.0   1.0  0.064971   0.001779    0.027387

[7456 rows x 5 columns]